# Generated by Django 5.0.2 on 2024-03-26 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='Место')),
                ('time', models.DateTimeField(verbose_name='Время')),
                ('action', models.TextField(verbose_name='Действие')),
                ('pleasant', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('frequency', models.CharField(choices=[('once_a_day', 'Один раз в день'), ('once_a_two_day', 'Один раз в два дня'), ('once_a_three_day', 'Один раз в три дня'), ('once_a_four_day', 'Один раз в четыре дня'), ('once_a_five_day', 'Один раз в пять дней'), ('once_a_six_day', 'Один раз в шесть дней'), ('once_a_seven_day', 'Один раз в семь дней')], verbose_name='Частота')),
                ('reward', models.CharField(max_length=100, verbose_name='Вознаграждение ')),
                ('estimated_time', models.TimeField(blank=True, null=True, verbose_name='Время на выполнение')),
                ('is_public', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('linked_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit')),
            ],
        ),
    ]
