# Generated by Django 5.0.2 on 2024-03-26 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.CharField(choices=[('once_a_day', 'Один раз в день'), ('once_a_week', 'Один раз в неделю'), ('once_a_month', 'Один раз в месяц'), ('once_a_year', 'Один раз в год')], verbose_name='Частота'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='linked_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='Связанная привычка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Вознаграждение'),
        ),
    ]
