# Generated by Django 5.0.2 on 2024-03-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_frequency_alter_habit_linked_habit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.CharField(choices=[('once_a_day', 'Один раз в день'), ('once_a_two_days', 'Один раз в два дня'), ('once_a_three_days', 'Один раз в три дня'), ('once_a_four_days', 'Один раз в четыре дня'), ('once_a_five_days', 'Один раз в пять дней'), ('once_a_six_days', 'Один раз в шесть дней'), ('once_a_week', 'Один раз в неделю')], default='once_a_day', verbose_name='Частота'),
        ),
    ]
